### ISSUE TITLE
Kick after Writing a message when the messages before were denied

### ISSUE THREAD

**Issue by Lorias-Jak** [4drian3d/UnSignedVelocity#32]
Good day ^^ 

I'm using UnSignedVelocity since recently and am just about to implement a mute-command in the plugin. Now I have the problem, if I mute the player everything works, no chat messages arrive. However, when I mute the player and he writes a message, he is kicked from the server with the error message shown below. Do you have any idea what the problem could be? 

<img width="1112" alt="image" src="https://github.com/4drian3d/UnSignedVelocity/assets/62625225/89c7b23d-9cf4-4ab0-b69f-b357ba1b995d">
<img width="419" alt="image" src="https://github.com/4drian3d/UnSignedVelocity/assets/62625225/d4e35e82-308c-4ff6-9375-352c317800aa">

<img width="933" alt="image" src="https://github.com/4drian3d/UnSignedVelocity/assets/62625225/07c34098-5e16-4cbc-85f8-dd0eeca1eb97">

**Comment by 4drian3d** [comment]
Known issue, use [SignedVelocity](https://modrinth.com/plugin/signedvelocity)
https://www.youtube.com/watch?v=5bfYy1kQwGk
